#! /bin/bash
input=$1
echo $input

if [[ -z $input ]]; then
    echo "Please rerun with the clone url of the repository you would like to clone"
    echo ""
    echo "Example:"
    echo "gh-clone git@github.com:migarjo/gh-clone"
    echo ""
    exit 1
fi  

if [[ $input == git@github.com:* ]]; then
    nwo="${input:15:${#input}-4}"
    nwo="${nwo::${#nwo}-4}"
elif [[ $input == https://github.com/* ]]; then
    nwo="${input:19:${#input}-4}"
    if [[ $nwo == *.git ]]; then
        nwo="${nwo::${#nwo}-4}"
    fi

fi

echo $nwo

IFS='/' read owner repo <<< "$nwo"

if [ ! -d "/Users/$USER/github/$owner" ]; then
    echo "no dir"
    mkdir "/Users/$USER/github/$owner"
fi
cd "/Users/$USER/github/$owner"

git clone "git@github.com:$owner/$repo.git"

if [ $? -eq 0 ]; then
    echo ""
    echo "To visit your repo, run:"
    echo "cd /Users/$USER/github/$owner/$repo"
else 
    echo "An error occurred while attempting to clone repo"
fi
